FROM node:12.16

RUN apk add --no-cache tzdata
ENV TZ America/Los_Angeles

RUN apk del tzdata

ARG NODE_ENV=development

RUN npm i npm@latest -g

RUN mkdir /opt/node && chown node:node /opt/node
WORKDIR /opt/node

COPY ./package.json ./package-lock.json* ./
RUN npm install --no-optional && npm cache clean --force
ENV PATH /opt/node/node_modules/.bin:$PATH

WORKDIR /opt/node/app

COPY . /opt/node/app